/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `/Chatlist`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyHotline`; params?: Router.UnknownInputParams; } | { pathname: `/Forgotpass`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LocationHistory`; params?: Router.UnknownInputParams; } | { pathname: `/Recoverypass`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Resources`; params?: Router.UnknownInputParams; } | { pathname: `/SafetyTips`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Account`; params?: Router.UnknownOutputParams; } | { pathname: `/Chat`; params?: Router.UnknownOutputParams; } | { pathname: `/Chatlist`; params?: Router.UnknownOutputParams; } | { pathname: `/EmergencyHotline`; params?: Router.UnknownOutputParams; } | { pathname: `/Forgotpass`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LocationHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/Recoverypass`; params?: Router.UnknownOutputParams; } | { pathname: `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/Resources`; params?: Router.UnknownOutputParams; } | { pathname: `/SafetyTips`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Account${`?${string}` | `#${string}` | ''}` | `/Chat${`?${string}` | `#${string}` | ''}` | `/Chatlist${`?${string}` | `#${string}` | ''}` | `/EmergencyHotline${`?${string}` | `#${string}` | ''}` | `/Forgotpass${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LocationHistory${`?${string}` | `#${string}` | ''}` | `/Recoverypass${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `/Resources${`?${string}` | `#${string}` | ''}` | `/SafetyTips${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `/Chatlist`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyHotline`; params?: Router.UnknownInputParams; } | { pathname: `/Forgotpass`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LocationHistory`; params?: Router.UnknownInputParams; } | { pathname: `/Recoverypass`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Resources`; params?: Router.UnknownInputParams; } | { pathname: `/SafetyTips`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
